# Make sure we’re using the latest Homebrew
brew update

# Use most recent version of vim
brew install vim --override-system-vi

# source control systems
brew install git
brew install git-extras

# youtube-dl and dependencies for post processing
# brew install youtube-dl
# brew install ffmpeg

# utilities
brew install asdf
brew install coreutils
brew install gpg
brew install pwgen
brew install ssh-copy-id
brew install urlview
brew install wget
brew install wifi-password
brew install z
brew install imagemagick

# JavasScript related stuff
brew install nvm
brew install node
brew install yarn

# databases
brew install postgresql
brew install sqlite3
brew install redis
brew install freetds

# servers
brew install nginx

brew install gifify
brew install svgo

# Remove outdated versions from the cellar
brew cleanup
